### ISSUE TITLE
do_gene_quantification fails in sc_long_pipeline

### ISSUE THREAD

**Issue by beeesal** [OliverVoogd/FLAMES#50]
Hey!
This is a great pipeline. I have been using sc_long_pipeline function and the gene quantification step fails. However, when I run this function with do_gene_quantification = FALSE in my configuration file, this step is skipped and the steps after this work. 

This is the error that I get:

10:02:37 Tue Oct 22 2024 Start gene quantification and UMI deduplication
10:02:37 Tue Oct 22 2024 quantify genes 
Found genome alignment file(s): 	align2genome.bam
No protocol specified
No protocol specified
Assigning reads to genes...
Processed:   0%|          | 1/20974 [00:00<3:14:58,  1.79gene_group/s]
Error in value[[3L]](cond) : Error when quantifying genes:
Traceback (most recent call last):
File "path to/FLAMES/python/count_gene.py", line 486, in quantification
quantify_gene(in_bam, annotation, n_process)
File "path to/FLAMES/python/count_gene.py", line 216, in quantify_gene
gene_count_mat, dedup_read_lst_sub, umi_list_sub = future.result()
ValueError: too many values to unpack (expected 3)

Also, when i set bambu_isoform_identification = TRUE in my config file, I get output files.
But when I try to set bambu_isoform_identification = FALSE and run the function, it fails with the following error:
Error: _Map_base::at

**Comment by ChangqingW** [comment]
I believe the `ValueError` has been fix on the Github devel branch, could you do `BiocManager::install("mritchielab/FLAMES")` and see if the error persist? You might also want to install the devel version of basilisk and basilisk.utils, either through bioconductor or `devtools::install_github('Bioconductor/basilisk.utils')` and `devtools::install_github('Bioconductor/basilisk')`

**Comment by beeesal** [comment]
I tried these steps and am encountering the same value error.

Found genome alignment file(s): 	align2genome.bam
Error in value[[3L]](cond) : Error when quantifying genes:
Traceback (most recent call last):
  File "/home/R/x86_64-pc-linux-gnu-library/4.4/reticulate/python/rpytools/loader.py", line 122, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/R/x86_64-pc-linux-gnu-library/4.4/reticulate/python/rpytools/loader.py", line 96, in _run_hook
    module = hook()
             ^^^^^^
  File "/home/R/x86_64-pc-linux-gnu-library/4.4/reticulate/python/rpytools/loader.py", line 120, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/R/x86_64-pc-linux-gnu-library/4.4/FLAMES/python/count_gene.py", line 8, in <module>
    import pandas as pd
  File "/home/R/x86_64-pc-linux-gnu-library/4.4/reticulate/python/rpytools/loader.py", line 122, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/R/x86_64-pc-linux-gnu-library

**Comment by ChangqingW** [comment]
Could you post the full error message? The last line does not look complete.

**Comment by beeesal** [comment]
I agree. I tried running this a couple of times but every time I get the same error and it ends the way shown above

**Comment by ChangqingW** [comment]
The `Error: _Map_base::at` is a known error we are trying to fix.

For the reticulate error, could you run `traceback()` after encountering the error and post the output? And `sessionInfo()` might also help.

**Comment by beeesal** [comment]
Thanks for your prompt response.

Posted the error below.

 Also, while quantifying transcripts (oarfish) is taking too long to run (24hours +) and I have to terminate it. I tried it out on a subset of my data so I'm working with a fastq of 600MB and a BAM file of around the same size. I did not have this issue with the previous version of FLAMES I used.
The isoforms generated from this pipeline are fine, it'd be great if the accompanying gene counts and transcript counts generate too.  Thanks :)

> traceback()
7: stop("Error when quantifying genes:\n", py_error_message)
6: value[[3L]](cond)
5: tryCatchOne(expr, names, parentenv, handlers[[1L]])
4: tryCatchList(expr, classes, parentenv, handlers)
3: tryCatch({
       basiliskRun(env = flames_env, fun = function(annotation, 
           outdir, pipeline, n_process, infq, samples, random_seed) {
           python_path <- system.file("python", package = "FLAMES")
           count <- reticulate::import_from_path("count_gene", python_path)
           count$quantification(annotation, outdir, pipeline, n_process, 
               infq = infq, sample_names = samples, random_seed = random_seed)
       }, annotation = annotation, outdir = outdir, pipeline = pipeline, 
           n_process = n_process, infq = infq, samples = samples, 
           random_seed = random_seed)
   }, error = function(e) {
       py_error <- reticulate::py_last_error()
       if (!is.null(py_error)) {
           py_error_message <- py_error$message
           cat(annotation, outdir, pipeline, n_process, infq, samples, 
               random_seed)
           stop("Error when quantifying genes:\n", py_error_message)
       }
       else {
           stop("Error when quantifying genes:\n", e$message)
    ...
2: quantify_gene(annotation, outdir, infq, config$pipeline_parameters$threads, 
       pipeline = "sc_single_sample", random_seed = random_seed)
1: sc_long_pipeline(annotation = gtf_anno_genome, fastq = ffq, outdir = "/bioinformatics/sample_files/", 
       genome_fa = fasta_genome, minimap2 = NULL, k8 = "/home/k8-0.2.4/k8-Linux", 
       config_file = config_path)

**Comment by youyupei** [comment]
Hi @beeesal, do you think you have the latest version of FLAMES? I think we have update the gene quantification very recently. Reinstall flames via `BiocManager::install("mritchielab/FLAMES")` might be helpful.

**Comment by beeesal** [comment]
Yes I'm running the function after reinstalling flames from BiocManager::install("mritchielab/FLAMES")
Just to confirm
> packageVersion("FLAMES")
[1] '2.1.1

I'm using R studio on a Linux system (20 cores and 50 G memory), Still getting stuck at generating transcript counts for a test file that is 600 Mb. Any recommendations?

**Comment by ChangqingW** [comment]
Hi Saloni, I think the issue you had with the oarfish quantification step was because the previous version of FLAMES had different FASTQ output that oarfish could not recognize. You could either:

1. re-run the blaze part and verify that the fastq files have the CB:Z:XXXX in the read ID field
2. modify your existing blaze output to add the required tag with sed or awk, for example:
```bash
awk 'NR % 4 == 1 {
    split($1, parts, "[@_#]");
    cell_barcode = parts[2];
    umi = parts[3];
    $1 = $1 "	CB:Z:" cell_barcode "	UB:Z:" umi;
} 1'  previous_demultipexed.fastq > new.fastq
```
The Fastq identifier filed should look like
```
@CGGGTCAGTAGTAGTA_CCGGGCTGTCTT#50409b8e-c5c8-4b86-8d2b-95effbb4434c_-1of1\tCB:Z:CGGGTCAGTAGTAGTA\tUB:Z:CCGGGCTGTCTT
```
where \t is a tab character

**Comment by josiegleeson** [comment]
Hi all, I'm getting the same error. I'm running this on the Melbourne Research Cloud servers so I wasn't sure if that was the issue somehow...

minimap2 runs successfully then this error occurs.

```
04:16:42 Mon Dec 09 2024 Start gene quantification and UMI deduplication
04:16:42 Mon Dec 09 2024 quantify genes 
Found genome alignment file(s): 	align2genome.bam
/srv/shiny-server/gencode.v47.annotation.gtf /srv/shiny-server/test_flames sc_single_sample 8 /srv/shiny-server/test_flames/matched_reads.fastq 2022Error in value[[3L]](cond) : Error when quantifying genes:
Traceback (most recent call last):
  File "/usr/local/lib/R/site-library/reticulate/python/rpytools/loader.py", line 122, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/R/site-library/reticulate/python/rpytools/loader.py", line 96, in _run_hook
    module = hook()
             ^^^^^^
  File "/usr/local/lib/R/site-library/reticulate/python/rpytools/loader.py", line 120, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/R/site-library/FLAMES/python/count_gene.py", line 5, in <module>
    import pysam
  File "/usr/local/lib/R/site-library/reticulate/python/rpytools/loader.py", line 122, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/R/site-library/reticulate/python/rpytools/loader.py", line 96, in _run_hook
    module = hook()
             ^^^^^^
  File "/
> traceback()
7: stop("Error when quantifying genes:\n", py_error_message)
6: value[[3L]](cond)
5: tryCatchOne(expr, names, parentenv, handlers[[1L]])
4: tryCatchList(expr, classes, parentenv, handlers)
3: tryCatch({
       basiliskRun(env = flames_env, fun = function(annotation, 
           outdir, pipeline, n_process, infq, samples, random_seed) {
           python_path <- system.file("python", package = "FLAMES")
           count <- reticulate::import_from_path("count_gene", python_path)
           count$quantification(annotation, outdir, pipeline, n_process, 
               infq = infq, sample_names = samples, random_seed = random_seed)
       }, annotation = annotation, outdir = outdir, pipeline = pipeline, 
           n_process = n_process, infq = infq, samples = samples, 
           random_seed = random_seed)
   }, error = function(e) {
       py_error <- reticulate::py_last_error()
       if (!is.null(py_error)) {
           py_error_message <- py_error$message
           cat(annotation, outdir, pipeline, n_process, infq, samples, 
               random_seed)
           stop("Error when quantifying genes:\n", py_error_message)
       }
       else {
           stop("Error when quantifying genes:\n", e$message)
    ...
2: quantify_gene(annotation, outdir, infq, config$pipeline_parameters$threads, 
       pipeline = "sc_single_sample", random_seed = random_seed)
1: sc_long_pipeline(annotation_file, "/srv/shiny-server/LongBench_ONT_sc_5000reads.fastq", 
       genome_bam = NULL, "/srv/shiny-server/test_flames", genome_file, 
       barcodes_file = NULL, expect_cell_number = 5000, config_file = NULL)
> sessionInfo()
R version 4.4.2 (2024-10-31)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 22.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C               LC_TIME=en_AU.UTF-8       
 [4] LC_COLLATE=en_AU.UTF-8     LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8   
 [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

time zone: Etc/UTC
tzcode source: system (glibc)

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] openssl_2.2.2                     BSgenome.Hsapiens.UCSC.hg38_1.4.5 BSgenome_1.74.0                  
 [4] rtracklayer_1.66.0                BiocIO_1.16.0                     Biostrings_2.74.0                
 [7] XVector_0.46.0                    SingleCellExperiment_1.28.1       SummarizedExperiment_1.36.0      
[10] Biobase_2.66.0                    GenomicRanges_1.58.0              GenomeInfoDb_1.42.1              
[13] IRanges_2.40.0                    S4Vectors_0.44.0                  BiocGenerics_0.52.0              
[16] MatrixGenerics_1.18.0             matrixStats_1.4.1                 FLAMES_2.0.1                     

loaded via a namespace (and not attached):
  [1] fs_1.6.4                  ProtGenerics_1.38.0       bitops_1.0-7              httr_1.4.7               
  [5] RColorBrewer_1.1-3        doParallel_1.0.17         tools_4.4.2               backports_1.4.1          
  [9] utf8_1.2.4                R6_2.5.1                  HDF5Array_1.34.0          lazyeval_0.2.2           
 [13] rhdf5filters_1.18.0       GetoptLong_1.0.5          withr_3.0.0               prettyunits_1.2.0        
 [17] GGally_2.2.1              gridExtra_2.3             cli_3.6.2                 scatterpie_0.2.4         
 [21] ggbio_1.54.0              readr_2.1.5               askpass_1.2.0             Rsamtools_2.22.0         
 [25] yulab.utils_0.1.8         txdbmaker_1.2.1           foreign_0.8-86            R.utils_2.12.3           
 [29] dichromat_2.0-0.1         scater_1.34.0             parallelly_1.40.1         limma_3.62.1             
 [33] rstudioapi_0.16.0         RSQLite_2.3.9             generics_0.1.3            shape_1.4.6.1            
 [37] dplyr_1.1.4               Matrix_1.6-5              ggbeeswarm_0.7.2          fansi_1.0.6              
 [41] abind_1.4-5               R.methodsS3_1.8.2         lifecycle_1.0.4           yaml_2.3.8               
 [45] edgeR_4.4.1               rhdf5_2.50.0              SparseArray_1.6.0         BiocFileCache_2.14.0     
 [49] grid_4.4.2                blob_1.2.4                dqrng_0.4.1               crayon_1.5.2             
 [53] dir.expiry_1.14.0         lattice_0.22-5            beachmat_2.22.0           cowplot_1.1.3            
 [57] GenomicFeatures_1.58.0    KEGGREST_1.46.0           magick_2.8.3              pillar_1.9.0             
 [61] knitr_1.46                ComplexHeatmap_2.22.0     metapod_1.14.0            bambu_3.8.0              
 [65] rjson_0.2.23              xgboost_1.7.8.1           codetools_0.2-19          glue_1.7.0               
 [69] ggfun_0.1.8               data.table_1.16.4         vctrs_0.6.5               png_0.1-8                
 [73] gtable_0.3.5              cachem_1.0.8              xfun_0.43                 S4Arrays_1.6.0           
 [77] DropletUtils_1.26.0       iterators_1.0.14          statmod_1.5.0             bluster_1.16.0           
 [81] bit64_4.0.5               progress_1.2.3            filelock_1.0.3            irlba_2.3.5.1            
 [85] vipor_0.4.7               rpart_4.1.23              colorspace_2.1-0          DBI_1.2.2                
 [89] Hmisc_5.2-1               nnet_7.3-19               tidyselect_1.2.1          bit_4.0.5                
 [93] compiler_4.4.2            curl_5.2.1                httr2_1.0.1               graph_1.84.0             
 [97] htmlTable_2.4.3           BiocNeighbors_2.0.1       basilisk.utils_1.18.0     xml2_1.3.6               
[101] DelayedArray_0.32.0       checkmate_2.3.2           scales_1.3.0              RBGL_1.82.0              
[105] rappdirs_0.3.3            stringr_1.5.1             SpatialExperiment_1.16.0  digest_0.6.35            
[109] rmarkdown_2.26            basilisk_1.18.0           htmltools_0.5.8.1         pkgconfig_2.0.3          
[113] base64enc_0.1-3           sparseMatrixStats_1.18.0  dbplyr_2.5.0              fastmap_1.1.1            
[117] ensembldb_2.30.0          rlang_1.1.3               GlobalOptions_0.1.2       htmlwidgets_1.6.4        
[121] UCSC.utils_1.2.0          DelayedMatrixStats_1.28.0 farver_2.1.2              jsonlite_1.8.8           
[125] BiocParallel_1.40.0       R.oo_1.26.0               BiocSingular_1.22.0       VariantAnnotation_1.52.0 
[129] RCurl_1.98-1.14           magrittr_2.0.3            Formula_1.2-5             scuttle_1.16.0           
[133] GenomeInfoDbData_1.2.13   Rhdf5lib_1.28.0           munsell_0.5.1             Rcpp_1.0.12              
[137] viridis_0.6.5             reticulate_1.40.0         stringi_1.8.4             zlibbioc_1.52.0          
[141] MASS_7.3-60.0.1           plyr_1.8.9                ggstats_0.7.0             parallel_4.4.2           
[145] listenv_0.9.1             ggrepel_0.9.6             hms_1.1.3                 circlize_0.4.16          
[149] locfit_1.5-9.10           igraph_2.0.3              reshape2_1.4.4            biomaRt_2.62.0           
[153] ScaledMatrix_1.14.0       XML_3.99-0.16.1           evaluate_0.23             biovizBase_1.54.0        
[157] scran_1.34.0              BiocManager_1.30.25       tzdb_0.4.0                foreach_1.5.2            
[161] tweenr_2.0.3              tidyr_1.3.1               purrr_1.0.2               polyclip_1.10-6          
[165] future_1.34.0             clue_0.3-66               ggplot2_3.5.1             ggforce_0.4.2            
[169] rsvd_1.0.5                restfulr_0.0.15           AnnotationFilter_1.30.0   viridisLite_0.4.2        
[173] OrganismDbi_1.48.0        tibble_3.2.1              memoise_2.0.1             beeswarm_0.4.0           
[177] AnnotationDbi_1.68.0      GenomicAlignments_1.42.0  cluster_2.1.6             globals_0.16.3  
```

My 'matched_reads.fastq' headers are as follows:
```
@CTGGTCTGTAACAAGT_GGGGCAGGTGAT#51f90d48-7ad0-4545-9f34-07c6941e7f00_+   CB:Z:CTGGTCTGTAACAAGT   UB:Z:GGGGCAGGTGAT
```

Thanks for any assistance with this.

**Comment by ChangqingW** [comment]
> Hi all, I'm getting the same error. I'm running this on the Melbourne Research Cloud servers so I wasn't sure if that was the issue somehow...
> 
> minimap2 runs successfully then this error occurs.
> 
> ```
> 04:16:42 Mon Dec 09 2024 Start gene quantification and UMI deduplication
> 04:16:42 Mon Dec 09 2024 quantify genes 
> Found genome alignment file(s): 	align2genome.bam
> /srv/shiny-server/gencode.v47.annotation.gtf /srv/shiny-server/test_flames sc_single_sample 8 /srv/shiny-server/test_flames/matched_reads.fastq 2022Error in value[[3L]](cond) : Error when quantifying genes:
> Traceback (most recent call last):
>   File "/usr/local/lib/R/site-library/reticulate/python/rpytools/loader.py", line 122, in _find_and_load_hook
>     return _run_hook(name, _hook)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/R/site-library/reticulate/python/rpytools/loader.py", line 96, in _run_hook
>     module = hook()
>              ^^^^^^
>   File "/usr/local/lib/R/site-library/reticulate/python/rpytools/loader.py", line 120, in _hook
>     return _find_and_load(name, import_)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/R/site-library/FLAMES/python/count_gene.py", line 5, in <module>
>     import pysam
>   File "/usr/local/lib/R/site-library/reticulate/python/rpytools/loader.py", line 122, in _find_and_load_hook
>     return _run_hook(name, _hook)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/R/site-library/reticulate/python/rpytools/loader.py", line 96, in _run_hook
>     module = hook()
>              ^^^^^^

Looks like the error was during loading the `pysam` package. If you do
```
conda activate ~/.cache/R/basilisk/1.17.2/FLAMES/2.1.2/flames_env # you might need to change the version number according to your installation
python3 -c 'import pysam; print(pysam.__version__)'
```
Would it give a version number without throwing errors?

**Comment by ChangqingW** [comment]
Not sure if you've got around the issue. If it persists, you could try adding `basilisk::setBasiliskFork(F)` before calling FLAMES functions.
